// Verbatim data extracted from org-of-the-future bundles (paths made relative).
export const badgeColors = ['#C0008D', '#6E2585', '#3667D9'];
export const cardBgs = ['#FAE0F1', '#EBE1F8', '#DEE8FC'];

export const icons = {
  compass: '<circle cx="12" cy="12" r="8.8"/><path d="M15.4 8.6l-2.1 4.7-4.7 2.1 2.1-4.7z"/>',
  spark: '<path d="M11 3.2l1.7 4.6 4.6 1.7-4.6 1.7L11 15.8 9.3 11.2 4.7 9.5l4.6-1.7z"/><path d="M17.6 15.1l.8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8z"/>',
  gear: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.6 1.6 0 0 0 .32 1.77l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06A1.6 1.6 0 0 0 15 19.4a1.6 1.6 0 0 0-1 1.47V21a2 2 0 0 1-4 0v-.09A1.6 1.6 0 0 0 9 19.4a1.6 1.6 0 0 0-1.77.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.6 1.6 0 0 0 4.6 15a1.6 1.6 0 0 0-1.47-1H3a2 2 0 0 1 0-4h.09A1.6 1.6 0 0 0 4.6 9a1.6 1.6 0 0 0-.33-1.77l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.6 1.6 0 0 0 9 4.6h.08A1.6 1.6 0 0 0 10 3.13V3a2 2 0 0 1 4 0v.09a1.6 1.6 0 0 0 1 1.47 1.6 1.6 0 0 0 1.77-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.6 1.6 0 0 0 19.4 9v.08a1.6 1.6 0 0 0 1.47 1H21a2 2 0 0 1 0 4h-.09a1.6 1.6 0 0 0-1.47 1z"/>',
  shield: '<path d="M12 3l7 3v5.2c0 4.8-3.4 8.3-7 9.8-3.6-1.5-7-5-7-9.8V6l7-3z"/><path d="M9.1 11.9l2.1 2.1 3.9-4"/>',
  cloud: '<path d="M7.2 18.5a4.6 4.6 0 0 1-.3-9.2A6.1 6.1 0 0 1 18 8.7a4.1 4.1 0 0 1-.4 9.8z"/>',
  db: '<ellipse cx="12" cy="6" rx="6.8" ry="2.8"/><path d="M5.2 6v12c0 1.5 3 2.8 6.8 2.8s6.8-1.3 6.8-2.8V6"/><path d="M5.2 12c0 1.5 3 2.8 6.8 2.8s6.8-1.3 6.8-2.8"/>',
  chart: '<path d="M4 3.5v17h16"/><path d="M8.2 17.2v-4.4M12 17.2V8.4M15.8 17.2v-6.6"/>',
  trend: '<path d="M4 4v16h16"/><path d="M7.2 16.2l3.6-3.9 2.8 2.4 4.6-5.5"/><circle cx="18.2" cy="9.2" r="1.5"/>',
  app: '<rect x="3.8" y="3.8" width="16.4" height="16.4" rx="3"/><path d="M3.8 9.2h16.4M9.2 9.2v11"/>',
  blocks: '<rect x="3.6" y="3.6" width="7.2" height="7.2" rx="1.8"/><rect x="13.2" y="3.6" width="7.2" height="7.2" rx="1.8"/><rect x="3.6" y="13.2" width="7.2" height="7.2" rx="1.8"/><rect x="13.2" y="13.2" width="7.2" height="7.2" rx="1.8"/>',
  net: '<circle cx="12" cy="5.2" r="2.4"/><circle cx="5.2" cy="18.4" r="2.4"/><circle cx="18.8" cy="18.4" r="2.4"/><path d="M10.8 7.4l-4.4 8.6M13.2 7.4l4.4 8.6M7.6 18.4h8.8"/>',
  route: '<circle cx="6" cy="6" r="2.6"/><circle cx="18" cy="18" r="2.6"/><path d="M8.6 6h4.6a3.6 3.6 0 0 1 0 7.2h-2.4a3.6 3.6 0 0 0 0 7.2"/>',
  server: '<rect x="3.8" y="4" width="16.4" height="6.6" rx="2"/><rect x="3.8" y="13.4" width="16.4" height="6.6" rx="2"/><path d="M7.4 7.3h.01M7.4 16.7h.01"/>',
  laptop: '<rect x="4.6" y="4.8" width="14.8" height="9.6" rx="1.8"/><path d="M2.8 18.4h18.4l-1.6-2.8H4.4z"/>',
  people: '<circle cx="8.8" cy="8.2" r="3.1"/><path d="M2.7 19.6c.5-3.4 3-5.6 6.1-5.6s5.6 2.2 6.1 5.6"/><circle cx="17" cy="9.6" r="2.3"/><path d="M16.2 14.2c2.6.3 4.6 2.4 5.1 5.4"/>',
  user: '<circle cx="12" cy="8.2" r="3.6"/><path d="M4.8 20c.8-3.8 3.6-6.2 7.2-6.2s6.4 2.4 7.2 6.2"/>',
  bot: '<rect x="3.8" y="7.8" width="16.4" height="11.4" rx="3.2"/><path d="M12 4.8v3M9.4 13h.01M14.6 13h.01M9.8 16.3h4.4"/><circle cx="12" cy="3.6" r="1.3"/>',
  grad: '<path d="M12 3.8L2.6 8.4 12 13l9.4-4.6z"/><path d="M6.6 11.1v4.6c0 1.5 2.4 2.7 5.4 2.7s5.4-1.2 5.4-2.7v-4.6"/><path d="M21.4 8.4v5.2"/>',
  lock: '<rect x="5.4" y="10.2" width="13.2" height="9.6" rx="2.2"/><path d="M8.6 10.2V7.6a3.4 3.4 0 0 1 6.8 0v2.6"/><path d="M12 14v2.2"/>',
  target: '<circle cx="12" cy="12" r="8.6"/><circle cx="12" cy="12" r="4.6"/><path d="M12 11.4h.01"/>',
  gauge: '<path d="M4 17.6a9 9 0 1 1 16 0"/><path d="M12 13.8l3.6-3.4"/><circle cx="12" cy="15.2" r="1.4"/>',
  coin: '<circle cx="12" cy="12" r="8.6"/><path d="M12 7v10"/><path d="M14.6 9.4a3 3 0 0 0-2.6-1.2c-1.7 0-2.8.8-2.8 2s1.1 1.9 2.8 1.9 2.8.7 2.8 1.9-1.1 2-2.8 2a3 3 0 0 1-2.6-1.2"/>',
  scale: '<path d="M12 4.4v15.2M8 19.6h8"/><path d="M4.6 8.2h14.8"/><path d="M2.2 14l2.4-5.8L7 14a2.4 2.4 0 0 1-4.8 0z"/><path d="M17 14l2.4-5.8L21.8 14a2.4 2.4 0 0 1-4.8 0z"/>',
  refresh: '<path d="M19.8 12a7.8 7.8 0 1 1-2.3-5.5"/><path d="M19.8 3.6v4.2h-4.2"/>',
  doc: '<path d="M6.8 3.2h7.4l4 4v13.6H6.8z"/><path d="M14.2 3.2v4h4"/><path d="M9.8 12.2h4.6M9.8 16h4.6"/>',
  eye: '<path d="M2.6 12S6.2 5.8 12 5.8 21.4 12 21.4 12 17.8 18.2 12 18.2 2.6 12 2.6 12z"/><circle cx="12" cy="12" r="3"/>',
  play: '<path d="M9 7.4l8 4.6-8 4.6z"/>'
};

export const departments = [
  { id: 'exec', label: 'Executive', name: 'Executives & Enterprise Enablement', leader: 'Office of the CEO', level: 8, icon: 'compass', photo: 'people/exec.png', squad: 'photos/svc-023.jpg', squadNote: 'Strategy pairing on the top floor', challenge: 'A backlog of AI ideas and no defensible way to decide what to fund first.', agents: [
    { name: 'RADIUS AI', status: 'live', icon: 'spark', desc: 'Position a high-touch rapid strategy & road-mapping engagement with senior business leaders, run as a fixed scope program.' },
    { name: 'AI Adoption & Change', status: 'live', icon: 'grad', bg: '#DEE8FC', desc: 'Position a training, adoption & change management (ACM) engagement to enable business users with AI.' }
  ], proof: ['A prioritized roadmap in days, not months.', 'A fixed four-week engagement: Align, Analyze, Design, Deliver.', 'A working technical proof of concept in as little as five days.'] },
  { id: 'hr', label: 'HR', name: 'People & Enablement', leader: 'CHRO', level: 7, icon: 'people', photo: 'people/hr.png', squad: 'photos/svc-007.jpg', squadNote: 'Flight Academy cohort, Level 1', challenge: 'Access to AI without adoption, so real usage stalls between 5 and 33 percent.', agents: [
    { name: 'AI Flight Academy', status: 'live', icon: 'grad', desc: 'A gamified AI enablement and adoption program, designed to make learning practical, engaging, and measurable.' }
  ], proof: ['13,400 graduates across all five levels.', '8,738 teammates completed Level 1 within 30 days.', "91 percent of teammates use AI daily at Insight, which is the program's own adoption anchor.", 'The move from about 20 percent to more than 80 percent active usage belongs to AI Continuous Adoption, the twelve-month engagement, not to Flight Academy.', 'Already sold to six clients, including Capital Power and Baker Tilly. Sold, which is not the same as adopted.'] },
  { id: 'it', label: 'Security', name: 'IT & Security', leader: 'CIO', level: 6, icon: 'server', photo: 'people/it.png', squad: 'photos/svc-121.jpg', squadNote: 'Platform squad on the floor', challenge: 'AI tool sprawl and shadow AI, with no single, secure place for teams to work.', agents: [
    { name: 'Enterprise AI Hub', status: 'live', icon: 'cloud', desc: 'Build a multi-modal AI platform leveraging guardrails, permissions, and governance controls.' },
    { name: 'Purview Information Protections Workshop', status: 'live', icon: 'lock', desc: 'Support organizations looking to establish baseline governance and security controls for AI.' }
  ], proof: ['Part of the surface behind 987,901 prompts in 28 days and 8,896 active users. That figure is org-wide across every AI tool, not Horizon alone.', 'The platform team moved from about 59 to 82 rolling velocity across six sprints.', 'Sprint carryover dropped from roughly 31 percent to under 5 percent.'] },
  { id: 'sec', label: 'IT Ops', name: 'IT Operations', leader: 'CTO', level: 5, icon: 'shield', photo: 'people/sec.png', squad: 'photos/svc-141.jpg', squadNote: 'Governance review in the operations bay', challenge: 'Agents are appearing everywhere with no approval, monitoring or off-ramp.', agents: [
    { name: 'Rapid AI', status: 'live', icon: 'spark', desc: 'Develop a rapid Proof of Concept (PoC) to validate and prove out business value for an AI Agent.' },
    { name: 'Agent Factory (DevShop)', status: 'live', icon: 'blocks', desc: 'Discover, intake, and rapidly prototype AI Agents that solve critical business challenges.' }
  ], proof: ['Fasken signed a sizable AI governance project with Agent 365 and the governance accelerator baked in, the first region globally to close a proper Agent 365 services deal.', 'Agent 365 is now a prerequisite for governed deployment, with E5 required as of June 1.', 'Copilot Studio agent security left Defender coverage on July 1, so a client running Copilot Studio agents without Agent 365 lost those protections that day.', 'An internal sandbox scan surfaced 142 agents, 31 unused in 30 days, 18 duplicates and 27 with no owner. Sample data from our own environment, not a customer estate.'] },
  { id: 'sales', label: 'Sales', name: 'Revenue & Sales', leader: 'CRO', level: 4, icon: 'trend', photo: 'people/sales.png', squad: 'photos/sme-01.jpg', squadNote: 'Pursuit desk, mid-quarter', challenge: 'Sellers drowning in RFPs and thin, manual opportunity capture.', agents: [
    { name: 'Rapid AI', status: 'live', icon: 'spark', desc: 'Develop a rapid Proof of Concept (PoC) to validate and prove out business value for an AI Agent.' },
    { name: 'Agent Factory (DevShop)', status: 'live', icon: 'blocks', desc: 'Discover, intake, and rapidly prototype AI Agents that solve critical business challenges.' }
  ], proof: ['Client Zero, in flight: both run in our own sales motion today, with no delivered client metric yet.', 'A sibling agent in the same suite holds 90 percent or better answer correctness.', 'Query response under 10 seconds and a full portfolio scan in about 45 seconds.'] },
  { id: 'ops', label: 'Logistics', name: 'Logistics & Supply Chain', leader: 'COO', level: 3, icon: 'gear', photo: 'people/ops.png', squad: 'photos/svc-011.jpg', squadNote: 'Command centre, live routing', challenge: 'Fragmented operational data and manual coordination across the value chain.', agents: [
    { name: 'Rapid AI', status: 'live', icon: 'spark', desc: 'Develop a rapid Proof of Concept (PoC) to validate and prove out business value for an AI Agent.' },
    { name: 'Agent Factory (DevShop)', status: 'live', icon: 'blocks', desc: 'Discover, intake, and rapidly prototype AI Agents that solve critical business challenges.' }
  ], proof: ['Built with the Mullen Group, starting from a failed proof of concept.', 'Narrowed to three agents across two business units, with a clear path to more than 30.', 'Compresses decision cycles from hours to minutes.'] },
  { id: 'legal', label: 'Legal', name: 'Legal & Risk', leader: 'General Counsel', level: 2, icon: 'scale', photo: 'people/legal.jpg', squad: 'photos/sme-22.jpg', squadNote: 'Clause review with counsel', challenge: 'Contract and SOW drafting is manual, slow and inconsistent across deals.', agents: [
    { name: 'Agentic Governance Accelerator', status: 'live', icon: 'lock', desc: 'Create, manage, and enforce responsible AI policies through the Microsoft E5. Provide clear guidance while supporting organizational governance, compliance, and risk management.' }
  ], proof: ['SOW creation time cut by half inside Insight. That is a Client Zero contracts function result, not a metric delivered by a named store agent. TBD: confirm this MVP is what produced it.', 'Standard language stays standard, so review effort concentrates on the exceptions.', 'Runs against the approved clause set, with counsel keeping the final word.'] },
  { id: 'fin', label: 'Finance', name: 'Finance', leader: 'CFO', level: 1, icon: 'coin', photo: 'people/fin.png', squad: 'photos/sme-18.jpg', squadNote: 'Consumption review, week two', challenge: 'AI is metered now, and consumption scales fast with no line of sight on spend.', agents: [
    { name: 'TokenScope MVP', status: 'beta', icon: 'gauge', desc: 'Coming soon!' }
  ], proof: ['Catches a runaway agent loop in hours instead of at the month-end invoice.', 'Keeps the roughly sevenfold token surge from multi-agent swarms visible and budgeted.', 'Turns AI consumption into a forecast finance can defend.'] },
  { id: 'hrops', label: 'PMO', name: 'PMO & People Operations', leader: 'CHRO', level: 0, icon: 'people', photo: 'people/hr.png', squad: 'photos/svc-007.jpg', squadNote: 'HR floor', challenge: 'TBD', agents: [
    { name: 'Rapid AI', status: 'live', icon: 'spark', desc: 'Develop a rapid Proof of Concept (PoC) to validate and prove out business value for an AI Agent.' },
    { name: 'Agent Factory (DevShop)', status: 'live', icon: 'blocks', desc: 'Discover, intake, and rapidly prototype AI Agents that solve critical business challenges.' }
  ], proof: [] }
];

export const indexStats = [
  { num: '91%', lbl: 'of teammates use AI daily', icon: 'people' },
  { num: '8,896', lbl: 'active users', icon: 'user' },
  { num: '987,901', lbl: 'prompts in 28 days', icon: 'spark' },
  { num: '30+', lbl: 'agents in production', icon: 'bot' }
];
export const indexFlags = { live: 'In production', beta: 'Beta', cz: 'Client Zero, in flight' };

// ---- client page data ----
export const LANDING_URL = 'TBD-LANDING-URL';
export const SFDC_CAMPAIGN = 'TBD-SFDC-CAMPAIGN-ID';
export const CAMPAIGN = 'agent-store-1.0';
export const clientFlags = { live: 'Available now', beta: 'Beta', cz: 'In flight inside Insight' };

export const clientStats = [
  { num: '987,901', lbl: 'prompts across Insight', note: '28-day window', icon: 'spark' },
  { num: '8,896', lbl: 'Insight teammates using it actively', note: 'Same window', icon: 'user' },
  { num: '30+', lbl: 'agents running in production', note: 'Our own estate', icon: 'bot' },
  { num: '13,400', lbl: "teammates trained through AI Flight Academy", note: "Insight's own program, all levels", icon: 'grad' }
];
export const statsSource = "Insight's own estate, August 2026. TBD: figures pending source owner sign-off before external release.";

const proofOverrides = {
  exec: ['A prioritized roadmap in days rather than months.', 'A fixed four-week engagement: Align, Analyze, Design, Deliver.', 'A working technical proof of concept in as little as five days.'],
  sec: ['A national Canadian law firm signed a sizable AI governance project with Agent 365 and this accelerator built in, the first Agent 365 services deal closed in the region.', 'Agent 365 is a prerequisite for governed deployment, and it requires E5 as of June 1.', 'Since July 1, Copilot Studio agent security requires Agent 365 and is no longer covered by existing Defender licences.'],
  it: ['Part of the platform surface behind 987,901 prompts in 28 days and 8,896 active users at Insight, a figure that covers every AI tool we run rather than this platform alone.', 'One secure multi-model surface, so teams stop reaching for unmanaged tools.', 'Usage measurement is built in, so adoption is visible from week one.'],
  fin: ['Catches a runaway agent loop in hours instead of at the month-end invoice.', 'Keeps the token surge from multi-agent workloads visible and budgeted.', 'Turns AI consumption into a forecast finance can defend.'],
  sales: ['Client Zero, in flight: both run in our own sales motion today, and neither has a delivered client metric yet.', 'Query response under 10 seconds, and a full portfolio scan in about 45 seconds.', 'Opportunity records arrive structured and enriched rather than typed from memory.'],
  ops: ['Built with a Canadian transportation and logistics group, starting from a proof of concept that had stalled.', 'Narrowed to three agents across two business units, with a path to more than 30.', 'Compresses operational decision cycles from hours to minutes.'],
  legal: ["Statement of work creation time cut by half inside Insight, achieved by our own contracts function.", 'Standard language stays standard, so review effort concentrates on exceptions.', 'Runs against your approved clause set, with counsel keeping the final word.'],
  hr: ['13,400 teammates trained at Insight, across every level of the program.', '8,738 of them completed Level 1 within 30 days.', '91 percent of Insight teammates use AI daily, which is what the program was built to produce.', 'Sold to six client organizations across energy and professional services. Sold rather than adopted, because those programs are still running.']
};
const ctaOverrides = { exec: 'Review your AI roadmap', sec: 'Book a governance review', it: 'See the platform', fin: 'Review your AI spend', sales: 'Walk your pursuit motion', ops: 'Map your operational data', legal: 'Review your contract flow', hr: 'Plan your adoption program' };
const agentOverrides = {
  TokenScope: { desc: 'Live budgets, real-time forecasting and full spend attribution, so every AI token traces to a project. Unattributed cost routes to its owner through the Spill Bucket. Currently in beta, which is why it is labelled as one.' },
  'AI Flight Academy': { desc: 'A gamified three-level adoption program that takes every teammate from a first prompt to certified champion, with completion tracked by cohort rather than by licence count.' },
  'Gen AI Auto Contract Creation MVP': { name: 'Contract and SOW drafting', desc: 'Assembles statements of work and contract language from approved clause libraries, flagging non-standard terms for counsel review instead of retyping them. This runs in our own contracts function today and is not yet a packaged store solution.' }
};
export const clientDepartments = departments.map(d => ({
  ...d,
  agents: d.agents.map(a => ({ ...a, ...(agentOverrides[a.name] ?? {}) })),
  proof: proofOverrides[d.id] ?? d.proof,
  cta: ctaOverrides[d.id] ?? 'Start a conversation'
}));

export const risk = {
  eyebrow: 'Read this first',
  head: 'Most agentic AI projects will not survive contact with production.',
  body: 'Gartner expects more than 40 percent of agentic AI projects to be cancelled by the end of 2027, and counts roughly 130 genuine agentic vendors among the thousands who describe themselves that way. You are right to assume most of what you are shown is a demo. So here is our position: we are not asking you to believe a claim, we are showing you the agents that run our own company and the numbers they move.',
  counters: [
    { num: '30+', lbl: 'agents in production at Insight, not in a lab', note: 'Our own estate, August 2026' },
    { num: '8', lbl: 'business functions running on them, including finance and legal', note: 'Our own estate, August 2026' },
    { num: '0', lbl: 'of the outcomes on this page come from a pilot we have not shipped', note: 'Production data or a signed engagement. Beta and in-flight solutions carry that label' }
  ]
};
export const standard = {
  head: 'How to read every number on this page',
  rules: ["Insight's own estate means our production data, with the measurement window stated.", 'A client result means a single signed engagement, described by sector until that client approves the reference by name.', 'Available now, beta and in flight are stated per solution. A beta is a beta on this page.', 'Where a number belongs to a different product in the same suite, we say which one rather than borrowing it.', 'Where we do not have a number yet, it says TBD rather than a rounded guess.', 'Any figure here will be shown to you with its query and its date range on request.']
};
export const commitments = [
  { num: '01', head: 'Fixed scope, fixed duration', body: 'Four weeks: Align, Analyze, Design, Deliver. A working technical proof of concept in as little as five days. If the scope moves, it moves in writing with a price attached.' },
  { num: '02', head: 'A baseline before we start', body: 'We measure your current state first and write it down. Without a baseline nobody can prove an outcome later, which is how pilots quietly become unfalsifiable.' },
  { num: '03', head: 'You own what we build', body: 'The agents run in your tenant, under your governance, against your data. No dependency on us to keep them running, and a documented off-ramp for every one.' },
  { num: '04', head: 'A named exit decision', body: 'Every engagement ends with a recorded go or no-go against the KPI we agreed, not with a renewal conversation and no verdict.' }
];
export const clientObjections = [
  { q: 'Everyone calls their product an agent now. Why is yours different?', a: 'Ours are the ones we could not do without. They handle our own governance, our own spend attribution, our own statement of work drafting and our own pursuit motion. If they stopped working tomorrow, Insight would feel it before you did. That is the only definition of production we accept.' },
  { q: 'Our last AI pilot went nowhere. Why would this be different?', a: 'Because the failure mode is almost never the model. It is the absence of a baseline, an owner and an exit decision. Our engagement fixes all three in the first week, and one of the eleven solutions here exists specifically to stop agent estates becoming unowned. We also started one of our best client outcomes from a proof of concept that had already stalled.' },
  { q: 'What stops this becoming another platform we cannot get out of?', a: 'The agents run in your tenant on Microsoft Agent 365 and your own governance controls. Every agent we deploy has a documented owner and a documented retirement path, because the alternative is the problem we sell against.' },
  { q: 'How fast do we know whether it is working?', a: 'You see the first governed agent inventory inside your own estate before the engagement is over, and the KPI table below tells you exactly which number should move and by when. If it has not moved, that is a no-go and we say so.' }
];
export const steps = [
  { step: 'Align', days: 'Week 1', body: 'Agree the problem, the baseline and the single KPI that decides success.' },
  { step: 'Analyze', days: 'Week 2', body: 'Scan the estate. You get the inventory whether or not you continue.' },
  { step: 'Design', days: 'Week 3', body: 'Target state, owner model and the retirement path for every agent.' },
  { step: 'Deliver', days: 'Week 4', body: 'Working proof of concept in your tenant, then the recorded go or no-go.' }
];
export const heroAgent = {
  floorId: 'sec', agentName: 'Agentic Governance Accelerator', platform: 'Built on Microsoft Agent 365',
  headline: 'Every agent in your estate, with an owner and an off-ramp.',
  problem: 'Agents are arriving through Copilot Studio, through vendors, and through teams who built their own. Most organizations cannot answer three questions about any of them: who owns this, is anyone using it, and how do we switch it off.',
  whyNow: ['Agent 365 is now a prerequisite for governed agent deployment, and it requires E5 as of June 1.', 'Since July 1, AI agent security for Copilot Studio agents requires Agent 365 and is no longer covered by existing Defender licences. Anyone running Copilot Studio agents without Agent 365 lost those protections that day.', 'Deployment ambition and operational readiness are moving in opposite directions across the market.'],
  evidence: {
    eyebrow: 'Delivered, not sampled', head: 'A Canadian law firm signed this, not a pilot of it.',
    body: 'A national Canadian law firm signed a sizable AI governance project with Agent 365 and this accelerator built in. It is the first Agent 365 services deal closed anywhere in the region, and the governance work is the reason it closed.',
    points: ['Agent 365 and the accelerator scoped together, not sold separately', 'Governance was the entry point, not an add-on at the end', 'First engagement of its kind in the region'],
    source: 'Signed client engagement, 2026. TBD: named reference pending client approval, suggested owner date 22 August.'
  },
  cta: 'Book a governance review',
  freeEntry: {
    eyebrow: 'No commitment', head: 'Start with the free assessment.',
    body: 'Run the free policy assessment against your own Microsoft 365 Copilot configuration. You get the assessment report preview at no cost and you keep it either way. If you decide to go further, we check whether partner funding covers the engagement before you spend anything.',
    steps: ['Free policy assessment, run against your own tenant configuration', 'Report preview to download, yours whether or not you continue', 'Funding eligibility checked before you commit to an engagement', 'Full report, gap analysis and implementation plan with the Accelerator'],
    cta: 'Run the free assessment'
  }
};
export const kpis = [
  { floorId: 'hrops', agent: 'Resource Intelligence', agentBullets: ['Faster time to response for staffing and capacity questions', 'Better allocation and utilization of project resources', 'Early identification of risk with staffing and project delivery'], supporting: [] },
  { floorId: 'sec', agent: 'Service Desk Assist', agentBullets: ['Time to triage and resolution', 'Percentage of simple issues deflected or resolved before human escalation', 'Request volume handled'], problem: 'Agents are multiplying across the estate faster than anyone can inventory them, and nobody can name an owner for most of them.', cost: 'Unowned agents are unmonitored agents. You are paying for duplicates, carrying licences nobody uses, and holding security exposure that Defender no longer covers for you.', primary: { kpi: 'Percentage of agents in the estate with a named owner and a retirement path', how: 'Agents with an assigned owner in Agent 365, divided by total agents discovered by scan.', baseline: 'Established by the scan in week 2, before anything is changed.', target: '100 percent of discovered agents owned or retired', signal: 'First full inventory inside the engagement' }, supporting: ['Agents retired as unused or duplicated, from a baseline the scan sets', 'Licence and consumption cost recovered from retired agents', 'Mean time to detect a new ungoverned agent appearing in the estate', 'Percentage of agents with an approved deployment record rather than an ad hoc one'] },
  { floorId: 'it', agent: 'Enterprise AI Hub', agentBullets: ['Zero data training: configure environments to ensure that proprietary data never leaks to public AI models', 'Role-based access control', '93% active use rate within 8 weeks within Insight'], problem: 'AI tool sprawl and shadow AI, with no single secure place for teams to work and no way to see what they are using.', cost: 'Every unmanaged tool is data leaving your control, spend outside your contracts, and a capability that cannot be reused by the next team that needs it.', primary: { kpi: 'Percentage of AI usage running on the governed platform', how: 'Active users on the governed platform, divided by total identified AI users across the organization.', baseline: 'Discovery of current tool usage in week 1.', target: 'TBD with the client, set against their current sprawl', signal: 'Usage visible from week one, because measurement is built in' }, supporting: ['Active usage rate, the share of licensed users actually working in it weekly', 'Number of agents reused by a second team rather than rebuilt', 'Time to stand up a new agent, from request to working', 'Cost per active user, trending down as usage concentrates'] },
  { floorId: 'fin', agent: 'TokenScope', agentBullets: ['Clear attribution of AI consumption to teams and business units', 'A shared source of truth for finance, technology, engineering, and operational leaders.', 'Reduced risk of unexpected spend', 'Clearer basis for forecasting, internal allocation, and chargeback'], problem: 'AI is metered now. Consumption scales faster than budget cycles and finance cannot attribute spend to anything a business case can defend.', cost: "A single runaway agent loop can consume a quarter's budget before the invoice arrives, and multi-agent workloads multiply token draw well beyond a single-agent forecast.", primary: { kpi: 'Percentage of AI spend attributed to a named project and owner', how: 'Attributed token spend divided by total token spend, with the remainder routed to its owner through the Spill Bucket.', baseline: 'Current attributable share, measured in week 1.', target: 'TBD with finance, typically the first goal is anything above zero', signal: 'Live budget view from the first week of instrumentation' }, supporting: ['Time to detect a runaway loop, hours rather than at month-end invoice', 'Forecast variance, forecast against actual consumption month over month', 'Cost per completed task, so spend can be compared to output', 'Share of workloads with a budget ceiling set before they run'] },
  { floorId: 'exec', agent: '', agentBullets: ['Faster time to proficiency for new hires', 'Active usage of published AI skills', 'Percentage of priority roles supported by reusable skills'], problem: 'A backlog of AI ideas competing for the same funding, and no defensible way to decide which ones to fund first.', cost: 'Decision latency. While the roadmap is argued, the budget goes to whoever is loudest, and the use cases with real value wait behind the ones with real sponsors.', primary: { kpi: 'Time from idea backlog to a scored, funded roadmap', how: 'Days from engagement start to a prioritized roadmap signed off by the funding decision maker.', baseline: 'How long the current backlog has been unresolved.', target: 'Days rather than months, inside a four-week fixed engagement', signal: 'A working technical proof of concept in as little as five days' }, supporting: ['Percentage of use cases carrying a business case that survives finance review', 'Number of ideas formally declined, which is the output people forget to count', 'Scored coverage across the seven-pillar Transformation Index', 'Time from roadmap sign-off to first agent in production'] },
  { floorId: 'ops', agent: 'Logistics AI Command Center', agentBullets: ['Reduced time from operational questions to answers', 'Reduced analyst hours spent on reporting', 'Improved asset, route, or fleet utilization'], problem: 'Operational data is fragmented across systems and coordinating an answer means a person chasing four teams.', cost: 'Decisions wait on people being available. Every hour a routing or asset question stays unanswered is an hour of capacity nobody can reclaim.', primary: { kpi: 'Operational decision cycle time', how: 'Median time from question asked to trusted answer returned, measured on the same question types before and after.', baseline: 'Current median, timed on live questions in week 1.', target: 'Hours compressed to minutes', signal: 'Live routing trace visible on every answer from day one' }, supporting: ['Share of questions answered without a human intermediary', 'Number of specialist agents in production, from a first three toward a mapped 30 or more', 'Answer correctness rate, sampled and reviewed by the business owner', 'Business units live, as a measure of whether the pattern travels'] },
  { floorId: 'sales', agent: 'Opportunity Desk', agentBullets: ['Simplify RFP intake-to-routing time from 5 business days to minutes', 'Reduce proposal cycle time', 'Return seller hours to customer-facing work'], problem: 'Sellers are drowning in inbound RFPs and opportunity capture is thin, manual and inconsistent between reps.', cost: 'Every RFP you decline for lack of capacity is a bid your competitor answers unopposed, and every opportunity typed from memory is a forecast built on a guess.', primary: { kpi: 'Percentage of inbound RFPs responded to', how: 'RFPs submitted divided by RFPs received, held against win rate so volume is not bought with quality.', baseline: 'Current response and decline rate over the last two quarters.', target: 'TBD with the client, set against their current decline rate', signal: 'First drafted response inside the first cycle' }, supporting: ['Hours of human effort per response, from assembly to submission', 'Answer correctness on retrieved content, sampled against the approved source', 'Time from client meeting to a structured, enriched opportunity in CRM', 'CRM field completeness on new opportunities, as a forecast quality proxy'] },
  { floorId: 'legal', agent: 'AI Policy Agent', agentBullets: ['Evaluate organization\u2019s AI policies against applicable legal, privacy, governance, and operational controls', 'Discovery & remediate identified gaps through Governance Accelerator Workshops'], problem: 'Statement of work and contract drafting is manual, slow, and inconsistent between deals, so legal becomes the bottleneck at the worst moment.', cost: 'Deals sit in legal while the quarter closes. Inconsistent language also means risk enters through drafting variance rather than through negotiation.', primary: { kpi: 'Statement of work cycle time', how: 'Median days from request to counsel-approved draft, on comparable deal types.', baseline: 'Current median, drawn from the last two quarters of deals.', target: "Cut by half, which is what Insight's own contracts function achieved", signal: 'First drafts inside the first week of use' }, supporting: ['That halving is a Client Zero result from our own contracts function, not a metric delivered by a packaged product', 'Percentage of drafts assembled from the approved clause library rather than retyped', 'Non-standard terms flagged for review, as a measure of what was previously missed', 'Counsel hours per deal, redirected from drafting to exceptions', 'Language consistency rate across deals of the same type'] },
  { floorId: 'hr', agent: 'AI Flight Academy', agentLead: 'Highlight that inside Insight, AI Flight Academy has helped:', agentBullets: ['More than 90% of employees to actively use AI', 'Generate nearly 1 million AI prompts in a 28-day period', 'Thousands of teammates progress through structured, traceable AI training'], problem: 'Everyone has access to AI and almost nobody is using it. Real adoption stalls somewhere between 5 and 33 percent while the licences are paid in full.', cost: 'You are carrying the full cost of the licence and capturing a fraction of the capability. Adoption, not access, is what converts AI spend into output.', primary: { kpi: 'Active usage rate', how: 'Teammates using AI weekly divided by teammates licensed, tracked by cohort through the three program levels.', baseline: 'Current active usage, measured before the program starts.', target: 'TBD with the client, set against the baseline. Insight reached 91 percent daily use', signal: 'Level 1 completion inside the first 30 days' }, supporting: ['The move from roughly 20 to more than 80 percent active usage is the published outcome of AI Continuous Adoption, the twelve-month engagement in the same suite, rather than a Flight Academy number', 'Level 1 completion within 30 days, against a cohort of 8,738 at Insight', 'Progression rate through the three program levels, from first prompt to certified champion', 'Share of teams with at least one certified champion', 'Prompts per active user, as a depth-of-use measure rather than a login count'] }
];
export const kpiFor = id => kpis.find(k => k.floorId === id);
export const videos = [
  { slug: 'ai-policy-agent', title: 'Agentic Governance Accelerator', assetName: 'AI Policy Agent', floorId: 'sec', runtime: '0:35', blurb: 'The free entry point. Run a policy assessment against your own Microsoft 365 Copilot setup, get the report preview, and see whether partner funding covers the engagement that follows.', src: 'videos/ai-policy-agent.mp4', mapping: 'confirmed', fr: 'october' },
  { slug: 'leaderos', title: 'PRISM and RADIUS AI', assetName: 'LeaderOS', floorId: 'exec', runtime: '0:41', blurb: 'The leadership view: what is running, what it produced, and what needs a decision this week.', src: 'videos/leaderos.mp4', mapping: 'confirmed', fr: 'october' },
  { slug: 'ai-skills-studio', title: 'AI Skills Studio', floorId: 'it', runtime: '0:59', blurb: 'Building, reusing and sharing agents across teams, so the second team does not rebuild what the first one shipped.', src: 'videos/ai-skills-studio.mp4', mapping: 'confirmed', fr: 'october' },
  { slug: 'service-desk-assist', title: 'Employee Assist', assetName: 'Service Desk Assist', floorId: 'it', runtime: '1:16', blurb: 'Help resolution and request fulfilment handled end to end, with escalation to a person when it should be. The resolution and response figures attached to this solution are targets, not delivered results, so they are not quoted here.', src: 'videos/service-desk-assist.mp4', mapping: 'tbd', fr: 'october' },
  { slug: 'tokenscope', title: 'TokenScope', floorId: 'fin', runtime: '0:52', blurb: 'Live budgets and spend attribution, so a runaway agent surfaces in hours instead of at the month-end invoice. Recorded against the current beta.', src: 'videos/tokenscope.mp4', mapping: 'confirmed', fr: 'october' },
  { slug: 'opportunity-desk', title: 'RFP Flow Engine and Pre-Sales Opportunity Agent', assetName: 'Opportunity Desk', floorId: 'sales', runtime: '1:27', blurb: 'An inbound RFP caught, drafted and enriched into a structured CRM opportunity without a rep retyping it. Both are running in our own sales motion now, which is why they are labelled in flight rather than proven.', src: 'videos/opportunity-desk.mp4', mapping: 'confirmed', fr: 'october' },
  { slug: 'logistics-command-center', title: 'Logistics AI Command Center', floorId: 'ops', runtime: '1:25', blurb: 'One plain-language question, classified by a supervisor agent and routed to the specialist that can answer it, with the routing trace visible.', src: 'videos/logistics-command-center.mp4', mapping: 'confirmed', fr: 'october' },
  { slug: 'flight-academy', title: 'AI Flight Academy', floorId: 'hr', runtime: '1:02', blurb: 'The adoption program in use, taking a teammate from a first prompt through to certified champion.', src: 'videos/flight-academy.mp4', mapping: 'confirmed', fr: 'october' }
];
export const demosFor = id => videos.filter(v => v.floorId === id && v.src);
export const videosNote = 'Recorded in live environments against real data. French recordings are restaged in a French environment rather than subtitled, and land in October. TBD: confirm against the French launch decision owned by Sunny Wang with Nick Stamadianos.';

// ---- seller page data ----
export const seller = {
  org: { org: 'Insight Canada', playbook: 'Insight Canada Playbook', market: 'the Canadian market' },
  notice: "Internal pre-sales tool for the September pilot. Not for screen-sharing with a customer yet. The client-facing page is marketing's public Agent Store page, and that is the link to send.",
  SUPPORT_URL: 'TBD-SUPPORT-INTAKE-URL',
  SOW_URL: 'TBD-SCRUB-SOW-LIBRARY-URL',
  what: {
    answer: "Agent Store 1.0 is Insight Canada's catalog of AI agents that already run our own company. Eleven solutions across eight business functions, each one deployed into the client's own tenant on Microsoft Agent 365, each one sold against a single primary KPI agreed before the work starts. It is not a reseller catalog of somebody else's agents. It is the estate we run Insight on, packaged so a client can take one function at a time.",
    talkTrack: { head: 'Say it in twenty seconds', body: 'Most vendors will show you a demo. We will show you the agents that run our finance, our legal, our security and our pursuit desk. Eight functions, more than thirty agents in production. You start with one, you measure one number, and you take the next one when the first has earned it.' },
    is: ['Eleven solutions across eight business functions, every one of them running inside Insight first.', 'Deployed into the client tenant on Microsoft Agent 365, under their governance and against their data.', 'Sold against one primary KPI per solution, with the calculation written down before the engagement starts.', 'A fixed four-week entry: Align, Analyze, Design, Deliver, ending in a recorded go or no-go.', "Evidenced by Insight's own production data, with the measurement window stated on every figure."],
    isNot: ['Not a reseller catalog. These are agents we built and operate, not agents we pass through.', 'Not a platform licence. The agents run in the client tenant, so there is a documented off-ramp for every one.', 'Not a pilot programme. Every engagement ends with a verdict against the KPI rather than a renewal conversation.', 'Not uniformly available. Three status labels are in use and they mean exactly what they say.', 'Not cleared for named client references yet. Use the sector wording until the approvals land.'],
    risk: {
      eyebrow: 'The room you are walking into', head: 'Your client has already been sold an agent that did not survive production.',
      body: 'Gartner expects more than 40 percent of agentic AI projects to be cancelled by the end of 2027, and counts roughly 130 genuine agentic vendors among the thousands who describe themselves that way. Assume your client is discounting everything you say by that rate. The counter is not a better claim, it is Client Zero: we are not asking them to believe us, we are showing them the agents that run our own company and the numbers they move.',
      counters: [
        { num: '40%+', lbl: 'of agentic AI projects expected to be cancelled by end of 2027', note: 'Gartner. TBD: confirm citation rights with Claire before external use' },
        { num: '~130', lbl: 'genuine agentic vendors out of thousands of claimants', note: 'Gartner. TBD: same citation check' },
        { num: '8', lbl: 'business functions at Insight running on these agents today', note: 'Our own estate, August 2026' }
      ]
    }
  },
  flags: {
    live: { internal: 'In production', external: 'Available now', rule: "Running in Insight's estate today. Safe to present as available." },
    beta: { internal: 'MVP Beta 1', external: 'Beta', rule: 'Say beta out loud. Do not say available now, and do not commit a general availability date.' },
    cz: { internal: 'Client Zero, in flight', external: 'In flight inside Insight', rule: 'Runs in our own motion, no delivered client metric yet. Do not say proven and do not quote a client outcome.' }
  },
  personas: [
    { floorId: 'hrops', persona: 'PMO Leaders, Resourcing Managers', cares: '', relevance: 'Resource Intelligence', relevanceDesc: 'Workforce and PMO leaders often cannot turn data into timely staffing decisions. Resource Intelligence brings together skills, capacity, availability, project, and project status to replace manual human review.', solves: [], offerings: [], references: [], sow: { label: '', ready: false } },
    { floorId: 'exec', persona: 'CEO, Chief Strategy Officer, Chief Transformation Officer, and all C-Suite Leaders', cares: 'Deciding which AI ideas get funded, and being able to defend that decision to a board.', relevance: 'AI Skills Studio', relevanceDesc: 'Capture expertise that lives with individual leaders and subject-matter experts, then turn it into reusable AI skills. Address knowledge concentration, inconsistent execution, slow onboarding, and the gap between access to AI and real task-level adoption.', runsOn: 'PRISM, delivered as the RADIUS AI engagement. An advisory motion, so there is nothing to deploy into the client tenant.', solves: ['A backlog of AI ideas with no defensible way to rank one against another.', 'Use cases with no business case that a finance team will actually accept.', 'Budget going to the loudest sponsor rather than to the highest value.'], offerings: [
      { name: 'RADIUS AI', kind: 'Engagement', note: 'The fixed-scope four-week strategy engagement wrapped around PRISM. Align, Analyze, Design, Deliver.', language: null },
      { name: 'PRISM Transformation Index scoring', kind: 'Assessment', note: 'Scores the idea backlog across seven pillars by value, feasibility and risk.', language: null },
      { name: 'Rapid POC', kind: 'Follow-on build', note: 'A working technical proof of concept in as little as five days, inside the same four weeks.', language: null },
      { name: 'Agent Factory', kind: 'Follow-on build', note: 'The build motion when the roadmap calls for several agents rather than one. Agent Factory questions route to Chris Holdsworth.', language: null }
    ], offeringsTbd: true, references: [], sow: { label: 'RADIUS AI scrub SOW', ready: false } },
    { floorId: 'sec', persona: 'Chief Information Officer, Chief Human Resources Officer, IT Directors', cares: 'Being accountable for agents nobody approved, in an estate they cannot inventory.', relevance: 'Service Desk Assist', relevanceDesc: 'Surface trusted answers, guide remediation, automate clearly defined requests, and direct unresolved issues to human support.', runsOn: "Microsoft Agent 365, deployed into the client's own tenant under their governance controls. Agent 365 requires E5 as of 1 June.", solves: ['Agents already running in the tenant with no owner and no inventory.', 'Copilot Studio agents outside Defender coverage since 1 July, which is a live exposure rather than a future risk.', 'No documented retirement path, so nothing can be switched off safely.'], offerings: [
      { name: 'Free policy assessment', kind: 'No commitment', note: "Runs against the client's own Microsoft 365 Copilot configuration and returns a report preview they keep either way. This is the productized loss leader and it should lead the conversation.", language: null },
      { name: 'Partner funding eligibility check', kind: 'Funding', note: 'Checked before the client commits spend. TBD: confirm against the Microsoft funding allocation owned by Paul Earhart with Claire, due 29 August.', language: null },
      { name: 'Agentic Governance Accelerator', kind: 'Engagement', note: 'Full report, gap analysis, implementation plan and the governed agent inventory in the client tenant.', language: null },
      { name: 'Agent 365 deployment services', kind: 'Deployment', note: 'Sold with the accelerator rather than after it. That pairing is why the first regional deal closed.', language: null }
    ], offeringsTbd: true, references: [{ account: 'Fasken', say: 'a national Canadian law firm', approved: false }], sow: { label: 'Agentic Governance Accelerator scrub SOW', ready: false } },
    { floorId: 'it', persona: 'Chief Information Officer, Chief Information Security Officer, and Head of Platform Engineering.', cares: 'Shadow AI, tool sprawl and having no single secure place for teams to build.', relevance: 'Enterprise AI Hub', relevanceDesc: 'Give organizations a proven starting point for operationalizing enterprise AI, reducing the time and complexity associated while ensuring security and governance.', runsOn: 'Horizon Enterprise AI Platform, a multi-model surface with an agent hub and usage measurement built in, with AI Skills Studio sitting on top of it.', solves: ['Shadow AI and tool sprawl that nobody in the organization can count.', 'Every team rebuilding an agent the last team already shipped.', 'Adoption reported as licences assigned rather than as weekly active use.'], offerings: [
      { name: 'Horizon Enterprise AI Platform', kind: 'Platform', note: 'One secure multi-model surface with an agent hub, file digestion and usage measurement built in.', language: null },
      { name: 'AI Skills Studio enablement', kind: 'Enablement', note: 'Stands up the build-and-reuse model, so the second team does not rebuild what the first team shipped.', language: null },
      { name: 'Agent Factory', kind: 'Follow-on build', note: 'The follow-on when a client wants several agents built rather than a platform stood up. Questions route to Chris Holdsworth.', language: null },
      { name: 'Employee Assist', kind: 'Solution', note: 'Help resolution and request fulfilment end to end. Filed internally as Service Desk Assist. TBD: floor mapping needs sign-off, flagged in Table C of the launch plan.', language: null }
    ], offeringsTbd: true, references: [], sow: { label: 'Horizon platform scrub SOW', ready: false } },
    { floorId: 'fin', persona: 'Chief Financial Officer, VP Finance, Directors of FP&A', cares: 'Attributing metered AI consumption to something a business case can defend.', relevance: 'TokenScope', relevanceDesc: 'Track AI consumption and spending across teams and applications. Control costs, improve accountability, and maximize the value of AI investments.', runsOn: "TokenScope, instrumented against the client's own AI consumption. TBD: confirm the deployment target and wave one inclusion with Jeremy Hodge, due 15 August.", solves: ['AI spend that cannot be attributed to a named project or owner.', 'A runaway agent loop that surfaces at the month-end invoice rather than in hours.', 'Forecasts that multi-agent token draw breaks well beyond a single-agent estimate.'], offerings: [
      { name: 'TokenScope', kind: 'Solution, beta', note: 'Live budgets, real-time forecasting and full spend attribution, with unattributed cost routed to its owner through the Spill Bucket.', language: null },
      { name: 'Spend attribution baseline', kind: 'Assessment', note: 'Measures the current attributable share in week one, which is the number the whole engagement is judged against.', language: null }
    ], offeringsTbd: true, references: [], sow: { label: 'TokenScope scrub SOW', ready: false } },
    { floorId: 'sales', persona: 'Chief Revenue Officer, VP Sales, General Manager', cares: 'Declining RFPs for lack of capacity, and a forecast built on opportunity records nobody trusts.', relevance: 'Opportunity Desk', relevanceDesc: 'Accelerate deal closure on RFPs from automated intake to research, proposal creation, and handoff.', runsOn: "The client's own CRM and content sources. TBD: confirm the deployment target with Sunny Wang before this is scoped on a live deal.", solves: ['Inbound RFPs declined for capacity rather than for fit.', 'Opportunity records typed from memory after the meeting.', 'Answer quality that varies by rep, with no approved source behind it.'], offerings: [
      { name: 'RFP Flow Engine', kind: 'Solution, in flight', note: 'Catches inbound RFPs and drafts responses, so more get answered with less manual assembly.', language: null },
      { name: 'Pre-Sales Opportunity Agent', kind: 'Solution, in flight', note: 'Reads a meeting transcript and builds a structured, enriched opportunity, including validation, funding checks and CRM creation.', language: null },
      { name: 'Rapid POC', kind: 'Follow-on build', note: 'The way to prove the motion on one deal type before committing the whole pursuit desk to it.', language: null }
    ], offeringsTbd: true, references: [], sow: { label: 'Pursuit motion scrub SOW', ready: false } },
    { floorId: 'ops', persona: 'Chief Operating Officer, VP Operations, VP Supply Chain', cares: 'Operational answers that wait on a person being available to chase four systems.', relevance: 'Logistics AI Command Center', relevanceDesc: 'Turn operational data into actionable answers. Get trusted insights across assets, clients, and inventory to make faster, more informed decisions.', runsOn: "A supervisor-and-specialist agent pattern deployed against the client's own operational systems, with the routing trace visible on every answer.", solves: ['Operational answers that wait on one overloaded person being available.', 'Data fragmented across systems that do not talk to each other.', 'A proof of concept that stalled, with nowhere obvious to take it next.'], offerings: [
      { name: 'Logistics AI Command Center', kind: 'Solution', note: 'A supervisor agent classifies each plain-language question and routes it to a specialist, returning a trusted answer with a live routing trace.', language: null },
      { name: 'Rapid POC', kind: 'Follow-on build', note: "Sunny's named follow-on for this floor. Proves one question type before the specialist estate is built out.", language: null },
      { name: 'Agent Factory', kind: 'Follow-on build', note: "Sunny's named follow-on when the client wants the specialist estate expanded. The delivered build went live with three specialists across two business units, with a mapped path to more than 30.", language: null }
    ], offeringsTbd: true, references: [{ account: 'Mullen Group', say: 'a Canadian transportation and logistics group', approved: false }], sow: { label: 'Command Center scrub SOW', ready: false } },
    { floorId: 'legal', persona: 'General Counsel, Chief Legal Officer, Chief Privacy Officer', cares: 'Being the bottleneck at quarter end, and risk entering through drafting variance.', relevance: 'AI Policy Agent', relevanceDesc: 'Many AI policies have not kept pace with AI use, evolving regulations, or the technical controls required to govern data. AI Policy Agent, used through Agentic Governance Workshops, helps to identify and prioritize gaps.', runsOn: "The client's own approved clause library. TBD: confirm the platform and the product name before this is shown as a store item.", solves: ['SOW drafting that becomes the bottleneck at quarter end.', 'Risk entering through drafting variance rather than through negotiation.', 'Counsel hours spent retyping standard language instead of reviewing exceptions.'], offerings: [
      { name: 'Clause library assessment', kind: 'Assessment', note: 'Establishes whether an approved clause set exists and is current, which is the precondition for anything else here.', language: null },
      { name: 'Gen AI Auto Contract Creation MVP', kind: 'Internal MVP', note: "Runs in Insight's own contracts function today. TBD: confirm the product name and confirm this MVP produced the 50 percent reduction before it is shown as a store item.", language: null },
      { name: 'Agent Factory', kind: 'Follow-on build', note: "Sunny's named follow-on for this floor: the route to take when legal wants several drafting agents built rather than one. Questions route to Chris Holdsworth.", language: null }
    ], offeringsTbd: true, references: [], sow: { label: 'Contract drafting scrub SOW', ready: false } },
    { floorId: 'hr', persona: 'CHRO, Chief People Officer, Chief Innovation Officer, Head of Learning', cares: 'Paying for AI licences in full while actual usage stalls in the low tens of percent.', relevance: 'AI Flight Academy', relevanceDesc: 'Build AI fluency through practical learning, guided workshops, and hands-on experiences so employees can adopt AI confidently and use it to support meaningful business outcomes.', runsOn: 'Delivered as a programme rather than as deployed software, so it runs against whatever AI tooling the client already licenses.', solves: ['Licences paid in full while real usage sits in the low tens of percent.', 'No champion model, so adoption stalls after the first prompt.', 'Enablement that cannot show what it measurably changed.'], offerings: [
      { name: 'AI Flight Academy', kind: 'Programme', note: 'A gamified adoption programme, three levels for clients and five internally, taking a teammate from a first prompt to certified champion.', language: null },
      { name: 'AI Continuous Adoption', kind: 'Engagement, twelve months', note: 'The twelve-month engagement in the same suite. This is the offering that owns the 20 to 80 percent active usage outcome, not Flight Academy.', language: null }
    ], offeringsTbd: true, references: [], sow: { label: 'Flight Academy scrub SOW', ready: false } }
  ],
  routing: [
    { when: 'What is Agent Factory, and anchor or technical questions', who: 'Chris Holdsworth', note: 'Goes straight to Chris rather than through the queue.' },
    { when: 'A question about how one specific agent works', who: 'The person who built it', note: "Sunny's team pulls the builder in, for example Jackson on the agents he built." },
    { when: 'Secure and Govern AI, and anything on the governance motion', who: 'Sunny Wang', note: 'The recommended hero agent sits on this floor, so most active deals land with Sunny and his team.' },
    { when: 'Anything else on an active deal', who: 'Sunny Wang and team', note: 'TBD: Sunny is building the Microsoft Form behind the support button and automating it to his inbox.' }
  ],
  refNote: 'Reference approvals for these accounts have no owner and no date in Table A of the launch plan. Suggested owner date 22 August. Until each one is approved, use the sector wording in every external setting, including verbal.',
  sowNote: 'TBD: scrub SOWs are pending upload. Anna Jabbari supplies the full offerings list and the SOW set once the Azure-hosted site is stood up. Access is pre-sales only.',
  // Section 03 — the conversation. Generic across floors: qualify the account,
  // run the first call, then earn the architecture session.
  entrySignalsLede: 'Prioritize accounts where you see one or more of the following:',
  entrySignals: [
    'An AI or Copilot pilot that never reached production',
    'A backlog of agent ideas without a delivery path',
    'Growing AI licences but limited evidence of business impact',
    'A named executive sponsor looking for a visible AI win',
    'A recurring manual process affecting cost, capacity, service, or decision speed',
    'A prior AI, data, cloud, security, PRISM, Horizon, or Flight Academy engagement',
    'Interest generated through an Agent Store demo, campaign, or event'
  ],
  entrySignalsNote: 'The existing sales guidance treats a stalled pilot, an executive sponsor, active AI investment, and a clearly named use case as the strongest qualification cues.',
  firstCall: [
    { head: 'Open with pressure', body: '"A lot of clients have invested in AI and generated plenty of ideas, but very few have a repeatable path into production. Where are you seeing that gap?"', bullets: [] },
    { head: 'Find the stuck use case', body: 'Ask what the business has already attempted, where it stalled, and who cares enough to fix it.', bullets: [] },
    { head: 'Establish the outcome', body: 'Agree on what would change if the use case worked:', bullets: ['Time returned', 'Faster decisions', 'Lower operating cost', 'Reduced risk', 'Better customer or employee service', 'Increased capacity', 'Greater accountability for AI spend'] },
    { head: 'Show one relevant solution', body: 'Choose the closest Agent Store example. Use it to demonstrate that Insight understands the pattern, not to imply that the client will receive an identical deployment.', bullets: [] },
    { head: 'Secure the next meeting', body: 'Bring in the appropriate architect or agent delivery lead to validate:', bullets: ['Business value', 'Data access', 'Integration requirements', 'Security and governance', 'Delivery approach', 'Funding eligibility', 'Production readiness'] }
  ],
  firstCallNote: 'The seller-enablement decks recommend a pressure, then outcome, then path conversation: diagnose what is stuck, define the desired business result, and then earn an architecture or scoping session.',
  sellerRule: 'Do not try to close an agent on the first call. Close the next conversation around a qualified business problem.',
  probeGroups: [
    { head: 'Business problem', items: ['What process is creating the most friction for the business today?', 'Where are employees still moving information between reports, inboxes, spreadsheets, and systems by hand?', 'Which decisions take too long because leaders cannot get a trusted answer quickly?', 'If you could remove one recurring task from a team this quarter, which one would have the greatest impact?', 'Which part of the business is actively asking for AI help today?'] },
    { head: 'Existing AI activity', items: ['Which AI or agent ideas have your teams already explored?', 'How many have reached production and are being used by the business?', 'Which experiment came closest to production, and what stopped it?', 'Where have you already invested in Copilot, Gemini, Azure, data, or other AI platforms?', 'Can leadership see a measurable return from that investment?'] },
    { head: 'Ownership and readiness', items: ['Who owns the agent backlog today: IT, the business, or a shared AI team?', 'Who would sponsor the first production use case?', 'Who would own the agent after launch?', 'Does your current team have the capacity to build, secure, monitor, and maintain agents?', 'What security, privacy, or compliance requirements need to be addressed before production?'] },
    { head: 'Value and urgency', items: ['What would a successful outcome look like in measurable terms?', 'What does the current process cost in time, delay, rework, or risk?', 'What happens if the problem remains unresolved for another six months?', 'Is there an executive commitment, renewal, budget cycle, or operational event creating urgency?', 'If you could put one agent into live business use first, which use case would you choose?'] },
    { head: 'Expansion questions', items: ['If the first agent works, which adjacent workflows would you tackle next?', 'Would you rather build an internal capability, use an ongoing Insight team, or combine both?', 'What data or platform modernization would make future agents easier to deploy?', 'How do you want to govern agents built by different teams or vendors?', 'Would a reusable roadmap be more valuable than treating every agent as a separate project?'] }
  ],
  probeGroupsNote: 'These questions build on the existing discovery guidance, which focuses on production status, stalled experiments, ownership, platform footprint, measurable return, and the next priority use case.',
  objections: [
    { q: 'We already have Claude, ChatGPT Enterprise, or Copilot.', say: 'That is a strong starting point. The next question is whether you are getting measurable business outcomes from it. Agent Store solutions help clients identify a proven use case, put the required data, workflow, security, and adoption around it, and move it into production.', redirect: 'Which Copilot use case has the clearest executive interest but has not reached production?' },
    { q: 'We can build this ourselves.', say: 'That may be the right long-term model. Insight can help you accelerate the first production use case, transfer proven design and delivery practices, and leave your team with a repeatable approach rather than long-term dependency.', redirect: 'Where would outside experience reduce risk or help your team move faster?' },
    { q: 'We do not want an off-the-shelf agent.', say: 'Neither do we. The catalog is a starting point, not a claim that every customer has the same environment. We reuse the proven pattern, architecture, documentation, and delivery assets, then adapt them to the client\u2019s data, workflows, controls, and operating model.', redirect: 'Which parts of this workflow are truly unique, and which parts are common across the industry?' },
    { q: 'Our data is not ready.', say: 'That is useful to know early. An agent can expose where data quality, access, integration, or governance is preventing the business from moving. We can scope the first use case around what is currently viable and build the data work into the broader roadmap.', redirect: 'Which data sources would the agent need, and who owns them today?' },
    { q: 'We do not have budget for another assessment.', say: 'Then we should not position another generic assessment. The goal is to identify a specific use case, a measurable outcome, and a credible path to something working. We should also validate relevant partner funding before presenting commercial options.', redirect: 'If we could offset part of the initial work and tie it to a production outcome, would that change the conversation?' },
    { q: 'Is the store limited to Microsoft?', say: 'The customer experience is organized around business challenges rather than product names. The first go-to-market motion is Microsoft-led, and many of the initial solutions use Microsoft technology, but the broader internal catalog also references other platforms and partner solutions. Do not promise a particular cloud provider until the architecture is validated.', redirect: 'Which platforms, data sources, and AI investments are already strategic in your environment?' },
    { q: 'Who supports the agent after deployment?', say: 'Support depends on the engagement model. It can include enablement of the client\u2019s own team, ongoing Insight managed services, or an embedded agent development team. We define ownership, monitoring, maintenance, and escalation as part of the production plan. The internal service model includes client enablement, managed services, and longer-running FDE teams as potential sustainment paths.', redirect: 'Do you want to own the capability internally, use an ongoing partner model, or combine the two?' }
  ],
  guard: [
    { wrong: 'One customer environment held 142 agents, 31 unused and 27 with no owner.', right: 'That scan ran in an internal sandbox, not a customer estate. It is sample data. The Security proof point is the signed law firm engagement instead.' },
    { wrong: 'TokenScope is available now.', right: "TokenScope is MVP Beta 1. Say beta. Wave one inclusion is Jeremy Hodge's decision, due 15 August." },
    { wrong: 'The Revenue agents are proven inside Insight.', right: 'In flight inside Insight. They run in our own motion and have no delivered client metric yet.' },
    { wrong: 'AI Flight Academy moves active usage from 20 to more than 80 percent.', right: "That outcome belongs to AI Continuous Adoption, the twelve-month engagement in the same suite. Flight Academy's own anchors are 13,400 graduates, 8,738 at Level 1 in 30 days, and 91 percent daily use at Insight." },
    { wrong: 'Flight Academy has five levels, from Gate Agent to Sky Maverick.', right: 'Five levels internally, three for clients. The level names are internal and do not go in a client conversation.' },
    { wrong: 'Our legal agent cuts SOW creation time by half.', right: "The 50 percent reduction is a Client Zero result from Insight's own contracts function. The artifact is the Gen AI Auto Contract Creation MVP owned by Dan Kronstal, not one of the eleven store solutions. Both still need confirming." },
    { wrong: 'Employee Assist resolves 80 percent of requests in under five seconds.', right: 'Those figures are targets, not delivered results. Do not quote them. The recording is filed under the working title Service Desk Assist.' },
    { wrong: '987,901 prompts and 8,896 users on the Horizon platform.', right: 'Those numbers are org-wide across every AI tool Insight runs, in a 28-day window, not the Horizon platform alone.' },
    { wrong: 'Four working titles used as product names: AI Policy Agent, LeaderOS, Opportunity Desk, Service Desk Assist.', right: 'The products are the Agentic Governance Accelerator, PRISM and RADIUS AI, RFP Flow Engine and Pre-Sales Opportunity Agent, and Employee Assist. The working titles are asset filenames, not names a client should hear.' }
  ],
  ways: [
    { head: 'Request support on your active deal', body: 'An open opportunity that needs a second set of hands on scoping, pricing or the response. Bring the account, the stage and what is blocking it.', context: 'active-deal' },
    { head: 'Contact an SME for your deal', body: 'A technical or solution question you need answered before the next meeting. Anchor and technical questions route to Chris Holdsworth. Secure and Govern AI routes to Sunny Wang.', context: 'sme' },
    { head: 'Get expert coaching on your Agent Store deal', body: 'A rehearsal before the meeting: the talk track, the objections you expect, and which floor to lead with for the stakeholder in the room.', context: 'coaching' }
  ],
  dates: [
    { when: '31 August 2026', what: 'Seller certification session' },
    { when: 'September 2026', what: 'Soft launch, five to ten design partners' },
    { when: '9 to 23 November 2026', what: 'Ignite amplification' }
  ]
};
export const personaFor = id => seller.personas.find(p => p.floorId === id);
